DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS player_game CASCADE;
DROP TABLE IF EXISTS words CASCADE;

DROP SEQUENCE IF EXISTS games_id;
DROP SEQUENCE IF EXISTS player_game_id;